# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            on the t
tagline:          'Tennis + Statistics'
url:              http://www.on_the_t.com
shorturl:         on_the_t.com

author:
  name:           'on the t'
  url:            https://twitter.com/_on_the_t

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/skoval/on_the_t

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
