# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
#title:            On the T
tagline:          'Tennis + Data + Statistics'
url:              http://on-the-t.com
shorturl:         on-the-t.com

author:
  name:           'On the T'
  url:            https://twitter.com/StatsOnTheT

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/on-the-t/on-the-t.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Contact: '/contact/'
  #Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
#gems:
#  - jekyll-redirect-from
